// Claim bundle builder — Phase 2.
//
// DETERMINISTIC BY DESIGN: this module assembles a claim-ready summary from
// stored rows. No LLM touches it. Money figures + medical context are exactly
// where a hallucination would be most damaging, and HSA GL-07-R2 favours
// "organising existing information" — so we organise, never generate.
// The family submits the bundle THEMSELVES; ALLY files nothing (PSA posture).

import type { Expense } from './types';
import { fmtSGD } from './wallet';

export interface ClaimBundleInput {
  patientName: string;
  diagnosis: string | null;
  destination: 'insurer' | 'medisave' | 'employer' | 'other';
  expenses: Expense[];
  preparedBy: string; // caregiver display name/email
  generatedAt: Date;
}

const DESTINATION_LABEL: Record<ClaimBundleInput['destination'], string> = {
  insurer: 'Insurance claim',
  medisave: 'MediSave / institution submission',
  employer: 'Employer benefits claim',
  other: 'Reimbursement claim',
};

export function buildClaimBundle(input: ClaimBundleInput): { text: string; totalCents: number } {
  const totalCents = input.expenses.reduce((acc, e) => acc + e.amount_cents, 0);
  const byCategory = new Map<string, number>();
  for (const e of input.expenses) {
    byCategory.set(e.category, (byCategory.get(e.category) ?? 0) + e.amount_cents);
  }

  const lines: string[] = [];
  lines.push(`${DESTINATION_LABEL[input.destination].toUpperCase()} — EXPENSE BUNDLE`);
  lines.push(`Generated by ALLY Care Wallet on ${input.generatedAt.toLocaleDateString('en-SG', { day: 'numeric', month: 'long', year: 'numeric' })}`);
  lines.push('');
  lines.push(`Care recipient: ${input.patientName}`);
  if (input.diagnosis) lines.push(`Diagnosis (as per hospital discharge document): ${input.diagnosis}`);
  lines.push(`Prepared by: ${input.preparedBy}`);
  lines.push('');
  lines.push(`ITEMISED EXPENSES (${input.expenses.length})`);
  lines.push('─'.repeat(46));
  for (const e of [...input.expenses].sort((a, b) => a.expense_date.localeCompare(b.expense_date))) {
    lines.push(`${e.expense_date}  ${e.merchant}`);
    lines.push(`  Category: ${e.category} · Amount: ${fmtSGD(e.amount_cents)}${e.source === 'receipt_snap' ? ' · receipt on file' : ''}`);
    if (e.receipt_quote) lines.push(`  Receipt total line: "${e.receipt_quote}"`);
  }
  lines.push('─'.repeat(46));
  lines.push('SUBTOTALS BY CATEGORY');
  // forEach instead of for...of: Map iteration needs an ES2015+ target,
  // and this project compiles to ES5 (same fix as lib/ratelimit.ts).
  byCategory.forEach((cents, cat) => lines.push(`  ${cat}: ${fmtSGD(cents)}`));
  lines.push(`TOTAL CLAIMED: ${fmtSGD(totalCents)}`);
  lines.push('');
  lines.push('NOTES');
  lines.push('• All amounts transcribed from original receipts (totals as printed; not recalculated).');
  lines.push('• Original receipts/photos available on request from the preparer.');
  lines.push('• This bundle was assembled from recorded expenses without AI generation.');
  lines.push('• Submit according to your policy/scheme requirements — ALLY does not file claims on your behalf.');

  return { text: lines.join('\n'), totalCents };
}
