-- ALLY Phase 2: claim bundles — deterministic, claim-ready expense summaries.
--
-- Design contract: bundles are ASSEMBLED from stored rows, never generated by
-- an LLM. Money figures + medical context demand determinism (SaMD posture:
-- organising existing information; accuracy posture: no hallucination surface).
-- The bundle is preparation material the family submits THEMSELVES to their
-- insurer / institution — ALLY files nothing and moves no money (PSA posture).

create table if not exists public.claim_bundles (
  id uuid primary key default gen_random_uuid(),
  care_plan_id uuid not null references public.care_plans(id) on delete cascade,
  created_by uuid not null references auth.users(id) on delete cascade,
  destination text not null default 'insurer' check (destination in ('insurer', 'medisave', 'employer', 'other')),
  expense_ids uuid[] not null,
  total_cents integer not null check (total_cents >= 0),
  bundle_text text not null,
  status text not null default 'draft' check (status in ('draft', 'submitted')),
  submitted_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists claim_bundles_plan_idx on public.claim_bundles (care_plan_id, created_at desc);

alter table public.claim_bundles enable row level security;

drop policy if exists claim_bundles_team_all on public.claim_bundles;
create policy claim_bundles_team_all on public.claim_bundles
  for all using (public.is_care_team_member(care_plan_id))
  with check (created_by = auth.uid() and public.is_care_team_member(care_plan_id));
